[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
BifurcationKit = "0f109fa4-8a5d-4b75-95aa-f515264e7665"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
